// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CreateVolume(arg1, arg2) {
  return window['go']['main']['App']['CreateVolume'](arg1, arg2);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DeleteVolume(arg1) {
  return window['go']['main']['App']['DeleteVolume'](arg1);
}

export function Explore(arg1) {
  return window['go']['main']['App']['Explore'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetSnapshots() {
  return window['go']['main']['App']['GetSnapshots']();
}

export function GetVolumes() {
  return window['go']['main']['App']['GetVolumes']();
}

export function InitConfigOnAlias(arg1, arg2) {
  return window['go']['main']['App']['InitConfigOnAlias'](arg1, arg2);
}

export function InitConfiguration(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitConfiguration'](arg1, arg2, arg3);
}

export function InitGlobalOptsOnExistingConfig() {
  return window['go']['main']['App']['InitGlobalOptsOnExistingConfig']();
}

export function OpenAllSnapshots() {
  return window['go']['main']['App']['OpenAllSnapshots']();
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenSnapshot(arg1) {
  return window['go']['main']['App']['OpenSnapshot'](arg1);
}

export function OpenVolume(arg1) {
  return window['go']['main']['App']['OpenVolume'](arg1);
}

export function Restore(arg1, arg2) {
  return window['go']['main']['App']['Restore'](arg1, arg2);
}

export function Store(arg1, arg2) {
  return window['go']['main']['App']['Store'](arg1, arg2);
}
