// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateVolume(arg1:string,arg2:string):Promise<string>;

export function Explore(arg1:string):Promise<main.Exploration>;

export function GetProgress():Promise<string>;

export function GetSnapshots():Promise<Array<any>>;

export function GetVolumes():Promise<Array<any>>;

export function InitConfigOnAlias(arg1:string,arg2:string):Promise<void>;

export function InitConfiguration(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InitGlobalOptsOnExistingConfig():Promise<Array<string>>;

export function OpenAllSnapshots():Promise<Array<main.FileForUI>>;

export function OpenDirectory():Promise<string>;

export function OpenSnapshot(arg1:string):Promise<Array<main.FileForUI>>;

export function OpenVolume(arg1:string):Promise<void>;

export function Restore(arg1:string,arg2:string):Promise<void>;

export function Store(arg1:string,arg2:Array<string>):Promise<Array<string>>;
